import argparse
import sys
import time
import json
import statistics
import subprocess
from pathlib import Path
from typing import Dict, List, Any, Optional

# We will run this script as a master script that invokes itself with different modes
# to ensure clean process state for vanilla vs patched vLLM.

def fmt_ms(value: Optional[float]) -> str:
    if value is None:
        return "not captured"
    return f"{value:.2f} ms"

def fmt_td_ms(value: Optional[float]) -> str:
    if value is None:
        return "N/A"
    return f"{value:.1f}"

def run_in_subprocess(mode: str, prompts: int) -> Dict[str, Any]:
    print(f"\n[BENCHMARK] Running mode: {mode} with {prompts} prompts...")
    cmd = [
        sys.executable, __file__,
        "--run-mode", mode,
        "--prompts", str(prompts),
        "--json-out", f"reports/bench_raw_{mode}.json"
    ]
    env = None
    subprocess.run(cmd, env=env, check=True)
    
    with open(f"reports/bench_raw_{mode}.json", "r") as f:
        return json.load(f)

def run_master(args):
    print("=" * 60)
    print(" Neural-Scalpel Precise Performance Regression ")
    print("=" * 60)
    
    Path("reports").mkdir(exist_ok=True)
    
    modes = [
        "A_vanilla",
        "B_base_route",
        "C_simulated_routes",
        "D_safetensors_routes",
        "E_mixed_route"
    ]
    
    results = {}
    for mode in modes:
        try:
            res = run_in_subprocess(mode, args.prompts)
            results[mode] = res
        except subprocess.CalledProcessError:
            print(f"[ERROR] Failed to run mode {mode}")
            results[mode] = {"error": "Failed"}
            
    # Output to markdown
    output_md = Path("docs/PRECISE_PERFORMANCE_REGRESSION.md")
    if not output_md.exists():
        output_md.parent.mkdir(exist_ok=True, parents=True)
        
    md_content = """# Precise Performance Regression Report

## Status

**Partially measured.**

This document is auto-generated by `scripts/bench_vllm_precise_latency.py`.
Mixed Route is tested as a 3-route mixed (base, real safetensors, simulated).

Completed:
- E2E p50 latency
- req/sec
- tok/sec
- VRAM peak
- internal swap p50 latency
- internal rollback p50 latency
- payload validation p50 latency

Pending:
- TTFT p50/p90/p99
- TPOT p50/p90/p99
- payload-load latency

## Results: TTFT / TPOT

> TTFT/TPOT are currently reported as `N/A` because this vLLM configuration did not expose `arrival_time`, `first_token_time`, and `finished_time` through `RequestOutput.metrics`. These remain pending until a direct vLLM timing hook or streaming-based measurement is added.

| Configuration | TTFT p50 (ms) | TTFT p90 (ms) | TTFT p99 (ms) | TPOT p50 (ms) | TPOT p90 (ms) | TPOT p99 (ms) |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
"""    
    for mode in modes:
        res = results.get(mode, {})
        if "error" in res:
            md_content += f"| {mode} | FAILED | - | - | - | - | - |\n"
            continue
        
        ttft_p50 = res.get("ttft_p50")
        ttft_p50_val = ttft_p50 * 1000 if ttft_p50 is not None else None
        ttft_p90 = res.get("ttft_p90")
        ttft_p90_val = ttft_p90 * 1000 if ttft_p90 is not None else None
        ttft_p99 = res.get("ttft_p99")
        ttft_p99_val = ttft_p99 * 1000 if ttft_p99 is not None else None
        
        tpot_p50 = res.get("tpot_p50")
        tpot_p50_val = tpot_p50 * 1000 if tpot_p50 is not None else None
        tpot_p90 = res.get("tpot_p90")
        tpot_p90_val = tpot_p90 * 1000 if tpot_p90 is not None else None
        tpot_p99 = res.get("tpot_p99")
        tpot_p99_val = tpot_p99 * 1000 if tpot_p99 is not None else None
        
        md_content += f"| {mode} | {fmt_td_ms(ttft_p50_val)} | {fmt_td_ms(ttft_p90_val)} | {fmt_td_ms(ttft_p99_val)} | {fmt_td_ms(tpot_p50_val)} | {fmt_td_ms(tpot_p90_val)} | {fmt_td_ms(tpot_p99_val)} |\n"
        
    md_content += "\n## Real Latency (GPU Tensor Cores)\n\n"
    
    # Extract internal latencies from E_mixed_route or D_safetensors_routes
    internal_res = results.get("E_mixed_route", {})
    if "error" in internal_res:
        internal_res = results.get("D_safetensors_routes", {})
        
    swap_ms = internal_res.get("swap_p50")
    rollback_ms = internal_res.get("rollback_p50")
    val_ms = internal_res.get("validation_p50")
    load_ms = internal_res.get("load_p50")
    
    md_content += f"- **Swap Latency p50**: {fmt_ms(swap_ms)}\n"
    md_content += f"- **Rollback Latency p50**: {fmt_ms(rollback_ms)}\n"
    md_content += f"- **Payload Validation p50**: {fmt_ms(val_ms)}\n"
    md_content += f"- **Payload Load (from disk to VRAM) p50**: {fmt_ms(load_ms)}\n"
    
    md_content += "\n## Other Metrics\n"
    for mode in modes:
        res = results.get(mode, {})
        if "error" in res: continue
        e2e = res.get("e2e_p50")
        e2e_val = e2e * 1000 if e2e is not None else None
        req_sec = res.get("req_sec", 0)
        vram = res.get("vram_peak_mb", 0)
        md_content += f"- **{mode}**: E2E p50 = {fmt_td_ms(e2e_val)} ms | {req_sec:.1f} req/s | VRAM Peak = {vram:.1f} MB\n"

    output_md.write_text(md_content, encoding='utf-8')
    print(f"\n[SUCCESS] Wrote results to {output_md}")


# --- Worker Mode ---
swap_latencies = []
rollback_latencies = []
validation_latencies = []
load_latencies = []

def instrument_runtime():
    """Monkey-patch HotSwapRuntime to measure internal GPU/CPU timings."""
    import torch
    try:
        from neural_scalpel.experimental.runtime import HotSwapRuntime
    except ImportError:
        return
        
    orig_apply_swap = HotSwapRuntime.apply_swap
    orig_perform_rollback = HotSwapRuntime._perform_rollback
    
    def hooked_apply_swap(self, route_data, validated_deltas=None):
        start_event = torch.cuda.Event(enable_timing=True)
        end_event = torch.cuda.Event(enable_timing=True)
        start_event.record()
        
        res = orig_apply_swap(self, route_data, validated_deltas)
        
        end_event.record()
        torch.cuda.synchronize()
        swap_latencies.append(start_event.elapsed_time(end_event))
        return res
        
    def hooked_perform_rollback(self, *args, **kwargs):
        start_event = torch.cuda.Event(enable_timing=True)
        end_event = torch.cuda.Event(enable_timing=True)
        start_event.record()
        
        res = orig_perform_rollback(self, *args, **kwargs)
        
        end_event.record()
        torch.cuda.synchronize()
        rollback_latencies.append(start_event.elapsed_time(end_event))
        return res
        
    HotSwapRuntime.apply_swap = hooked_apply_swap
    HotSwapRuntime._perform_rollback = hooked_perform_rollback
    
    # We can also patch validate_payload / load_payload_deltas if imported
    try:
        import neural_scalpel.route.payload_validator as pv
        orig_validate = pv.validate_payload
        def hooked_validate(*args, **kwargs):
            t0 = time.perf_counter()
            res = orig_validate(*args, **kwargs)
            validation_latencies.append((time.perf_counter() - t0) * 1000)
            return res
        pv.validate_payload = hooked_validate
    except AttributeError:
        pass

    try:
        import neural_scalpel.route.payload as pyld
        orig_load = pyld.load_payload_deltas
        def hooked_load(*args, **kwargs):
            t0 = time.perf_counter()
            res = orig_load(*args, **kwargs)
            load_latencies.append((time.perf_counter() - t0) * 1000)
            return res
        pyld.load_payload_deltas = hooked_load
    except AttributeError:
        pass

def sha256_file(path):
    import hashlib
    from pathlib import Path

    path = Path(path)
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()

def ensure_benchmark_payload():
    from pathlib import Path
    import hashlib

    candidate_paths = [
        Path("vllm_registry_storage/payloads/opt125m_sql_delta.safetensors"),
        Path("integrations/vllm_route_plugin/tests/fixtures/opt125m_sql_delta.safetensors"),
        Path("tests/fixtures/opt125m_sql_delta.safetensors"),
    ]

    # 1. Prefer ensure_test_payload if available.
    try:
        from integrations.vllm_route_plugin.tests.gen_test_payload import ensure_test_payload
        result = ensure_test_payload()

        if isinstance(result, tuple) and len(result) == 2:
            return str(result[0]), result[1]

        if result is not None:
            payload_path = Path(result)
            return str(payload_path), sha256_file(payload_path)
    except ImportError:
        pass

    # 2. Fall back to generate_test_payload, even if it returns None.
    try:
        from integrations.vllm_route_plugin.tests.gen_test_payload import generate_test_payload
        result = generate_test_payload()

        if isinstance(result, tuple) and len(result) == 2:
            return str(result[0]), result[1]

        if result is not None:
            payload_path = Path(result)
            return str(payload_path), sha256_file(payload_path)
    except ImportError:
        pass

    # 3. Search known generated locations.
    for path in candidate_paths:
        if path.exists():
            return str(path), sha256_file(path)

    raise FileNotFoundError(
        "Could not locate benchmark safetensors payload. "
        "Expected one of: "
        + ", ".join(str(p) for p in candidate_paths)
    )

def run_worker(args):
    import torch
    from vllm import LLM, SamplingParams
    
    mode = args.run_mode
    
    if mode != "A_vanilla":
        from integrations.vllm_route_plugin.patch import apply_all_patches
        from integrations.vllm_route_plugin.runtime_context import get_vllm_registry
        
        apply_all_patches()
        instrument_runtime()
        
        registry = get_vllm_registry()
        target_layers = [{
            "name": "model.decoder.layers.0.self_attn.qkv_proj.weight",
            "shape": [2304, 768],
            "dtype": "float16"
        }]

        if mode in {"C_simulated_routes", "E_mixed_route"}:
            registry.routes["simulated-route"] = {
                "route_id": "simulated-route",
                "tenant_id": "bench",
                "layers": target_layers,
                "payload_type": "simulated"
            }

        if mode in {"D_safetensors_routes", "E_mixed_route"}:
            payload_uri, payload_sha256 = ensure_benchmark_payload()

            registry.routes["sql-route"] = {
                "route_id": "sql-route",
                "tenant_id": "bench",
                "layers": target_layers,
                "payload_type": "real",
                "payload": {
                    "format": "safetensors",
                    "uri": payload_uri,
                    "sha256": payload_sha256,
                }
            }
        
    print(f"[WORKER] Initializing Engine for {mode}...")
    vram_initial = torch.cuda.memory_reserved() / 1024**2 if torch.cuda.is_available() else 0.0
    
    llm = LLM(model="facebook/opt-125m", enforce_eager=True)
    
    prompts = ["List the prime numbers up to 100."] * args.prompts
    
    sps = []
    routes = ["__base__", "sql-route", "simulated-route"]
    for i in range(args.prompts):
        sp = SamplingParams(max_tokens=32, temperature=0.0)
        
        if mode == "B_base_route":
            sp.extra_args = {"route_id": "__base__"}
        elif mode == "C_simulated_routes":
            sp.extra_args = {"route_id": "simulated-route"}
        elif mode == "D_safetensors_routes":
            sp.extra_args = {"route_id": "sql-route"}
        elif mode == "E_mixed_route":
            sp.extra_args = {"route_id": routes[i % len(routes)]}
            
        sps.append(sp)
        
    print("[WORKER] Generating...")
    
    t0 = time.perf_counter()
    outputs = llm.generate(prompts, sps, use_tqdm=False)
    t1 = time.perf_counter()
    
    vram_peak = torch.cuda.memory_reserved() / 1024**2 if torch.cuda.is_available() else 0.0
    
    ttfts = []
    tpots = []
    e2es = []
    total_tokens = 0
    
    for out in outputs:
        # Extract TTFT/TPOT from RequestOutput.metrics if available
        metrics = getattr(out, 'metrics', None)
        if metrics is not None:
            arrival = getattr(metrics, 'arrival_time', None)
            first_tok = getattr(metrics, 'first_token_time', None)
            finished = getattr(metrics, 'finished_time', None)
            
            if arrival and first_tok and finished:
                ttfts.append(first_tok - arrival)
                e2es.append(finished - arrival)
                
                output_len = len(out.outputs[0].token_ids)
                if output_len > 1:
                    tpots.append((finished - first_tok) / (output_len - 1))
                else:
                    tpots.append(0.0)
        
        total_tokens += len(out.outputs[0].token_ids)
        
    e2e_total = t1 - t0
    req_sec = args.prompts / e2e_total if e2e_total > 0 else 0
    tok_sec = total_tokens / e2e_total if e2e_total > 0 else 0
    
    def percentile(lst, p):
        if not lst: return None
        s = sorted(lst)
        k = (len(s) - 1) * p
        f = int(k)
        c = min(f + 1, len(s) - 1)
        return s[f] + (k - f) * (s[c] - s[f])

    results = {
        "ttft_p50": percentile(ttfts, 0.5),
        "ttft_p90": percentile(ttfts, 0.9),
        "ttft_p99": percentile(ttfts, 0.99),
        "tpot_p50": percentile(tpots, 0.5),
        "tpot_p90": percentile(tpots, 0.9),
        "tpot_p99": percentile(tpots, 0.99),
        "e2e_p50": percentile(e2es, 0.5) if e2es else (e2e_total / args.prompts if args.prompts > 0 else None),
        "req_sec": req_sec,
        "tok_sec": tok_sec,
        "vram_initial_mb": vram_initial,
        "vram_peak_mb": vram_peak,
        "swap_p50": percentile(swap_latencies, 0.5),
        "rollback_p50": percentile(rollback_latencies, 0.5),
        "validation_p50": percentile(validation_latencies, 0.5),
        "load_p50": percentile(load_latencies, 0.5),
    }
    
    with open(args.json_out, "w") as f:
        json.dump(results, f, indent=2)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-mode", type=str, default="master")
    parser.add_argument("--prompts", type=int, default=50)
    parser.add_argument("--json-out", type=str, default="reports/bench_raw.json")
    args = parser.parse_args()
    
    if args.run_mode == "master":
        run_master(args)
    else:
        run_worker(args)
